apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - client-config-configmap.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: risk-answers-client-deployment
    path: patch-image-with-gar-and-version.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: risk-answers-client-deployment
    path: patch-replace-client-config.yaml 