- op: add
  path: /spec/template/spec/volumes
  value:
    - name: config-volume
      configMap:
        name: risk-answers-client-config

- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: config-volume
      mountPath: /usr/share/nginx/html/config