apiVersion: v1
kind: PersistentVolume
metadata:
  name: monorepo-starter-mongo-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/monorepo-starter-mongo-pv

