apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monorepo-starter-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 200Mi
