apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: risk-answers-api-deployment
    path: patch-add-env-vars.yaml 