apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-standard-storage-class
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard # Other Options supported are pd-ssd, pd-balanced
