apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/client

components:
  - ../../components/client/gke
  - ../../components/client/change-client-to-serve-site-via-nginx

commonLabels:
  env: prod 